apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gen3-arranger.fullname" . }}
  labels:
    app: {{ template "gen3-arranger.name" . }}
    chart: {{ template "gen3-arranger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gen3-arranger.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gen3-arranger.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "gen3-arranger.name" . }}
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.volumes }}
      volumes:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /_status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 3000
          env:
          - name: GEN3_ES_ENDPOINT
            value: esproxy-service:9200
          - name: GEN3_ARBORIST_ENDPOINT
            value: http://arborist-service
          - name: GEN3_PROJECT_ID
            value: {{ .Values.arrangerProjectId }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.volumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
    {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
